//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Secv.Ng.Manutencao.CadeiaAutorizacao {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("CadeiaAutorizacaoDataSet")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class CadeiaAutorizacaoDataSet : System.Data.DataSet {
        
        private ParemetroFuncaoHierarquiaDataTable tableParemetroFuncaoHierarquia;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CadeiaAutorizacaoDataSet() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected CadeiaAutorizacaoDataSet(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["ParemetroFuncaoHierarquia"] != null)) {
                    base.Tables.Add(new ParemetroFuncaoHierarquiaDataTable(ds.Tables["ParemetroFuncaoHierarquia"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public ParemetroFuncaoHierarquiaDataTable ParemetroFuncaoHierarquia {
            get {
                return this.tableParemetroFuncaoHierarquia;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            CadeiaAutorizacaoDataSet cln = ((CadeiaAutorizacaoDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["ParemetroFuncaoHierarquia"] != null)) {
                    base.Tables.Add(new ParemetroFuncaoHierarquiaDataTable(ds.Tables["ParemetroFuncaoHierarquia"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableParemetroFuncaoHierarquia = ((ParemetroFuncaoHierarquiaDataTable)(base.Tables["ParemetroFuncaoHierarquia"]));
            if ((initTable == true)) {
                if ((this.tableParemetroFuncaoHierarquia != null)) {
                    this.tableParemetroFuncaoHierarquia.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "CadeiaAutorizacaoDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/CadeiaAutorizacaoDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableParemetroFuncaoHierarquia = new ParemetroFuncaoHierarquiaDataTable();
            base.Tables.Add(this.tableParemetroFuncaoHierarquia);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeParemetroFuncaoHierarquia() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            CadeiaAutorizacaoDataSet ds = new CadeiaAutorizacaoDataSet();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void ParemetroFuncaoHierarquiaRowChangeEventHandler(object sender, ParemetroFuncaoHierarquiaRowChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class ParemetroFuncaoHierarquiaDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnnome;
            
            private System.Data.DataColumn columnvalor;
            
            private System.Data.DataColumn columntipo;
            
            private System.Data.DataColumn columntamanho;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ParemetroFuncaoHierarquiaDataTable() {
                this.TableName = "ParemetroFuncaoHierarquia";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal ParemetroFuncaoHierarquiaDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected ParemetroFuncaoHierarquiaDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn nomeColumn {
                get {
                    return this.columnnome;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn valorColumn {
                get {
                    return this.columnvalor;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn tipoColumn {
                get {
                    return this.columntipo;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn tamanhoColumn {
                get {
                    return this.columntamanho;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ParemetroFuncaoHierarquiaRow this[int index] {
                get {
                    return ((ParemetroFuncaoHierarquiaRow)(this.Rows[index]));
                }
            }
            
            public event ParemetroFuncaoHierarquiaRowChangeEventHandler ParemetroFuncaoHierarquiaRowChanging;
            
            public event ParemetroFuncaoHierarquiaRowChangeEventHandler ParemetroFuncaoHierarquiaRowChanged;
            
            public event ParemetroFuncaoHierarquiaRowChangeEventHandler ParemetroFuncaoHierarquiaRowDeleting;
            
            public event ParemetroFuncaoHierarquiaRowChangeEventHandler ParemetroFuncaoHierarquiaRowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddParemetroFuncaoHierarquiaRow(ParemetroFuncaoHierarquiaRow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ParemetroFuncaoHierarquiaRow AddParemetroFuncaoHierarquiaRow(string nome, object valor, string tipo, string tamanho) {
                ParemetroFuncaoHierarquiaRow rowParemetroFuncaoHierarquiaRow = ((ParemetroFuncaoHierarquiaRow)(this.NewRow()));
                rowParemetroFuncaoHierarquiaRow.ItemArray = new object[] {
                        nome,
                        valor,
                        tipo,
                        tamanho};
                this.Rows.Add(rowParemetroFuncaoHierarquiaRow);
                return rowParemetroFuncaoHierarquiaRow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ParemetroFuncaoHierarquiaRow FindBynome(string nome) {
                return ((ParemetroFuncaoHierarquiaRow)(this.Rows.Find(new object[] {
                            nome})));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                ParemetroFuncaoHierarquiaDataTable cln = ((ParemetroFuncaoHierarquiaDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new ParemetroFuncaoHierarquiaDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnnome = base.Columns["nome"];
                this.columnvalor = base.Columns["valor"];
                this.columntipo = base.Columns["tipo"];
                this.columntamanho = base.Columns["tamanho"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnnome = new System.Data.DataColumn("nome", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnnome);
                this.columnvalor = new System.Data.DataColumn("valor", typeof(object), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnvalor);
                this.columntipo = new System.Data.DataColumn("tipo", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columntipo);
                this.columntamanho = new System.Data.DataColumn("tamanho", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columntamanho);
                this.Constraints.Add(new System.Data.UniqueConstraint("ParemetroFuncaoHierarquiaKey1", new System.Data.DataColumn[] {
                                this.columnnome}, true));
                this.columnnome.AllowDBNull = false;
                this.columnnome.Unique = true;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ParemetroFuncaoHierarquiaRow NewParemetroFuncaoHierarquiaRow() {
                return ((ParemetroFuncaoHierarquiaRow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new ParemetroFuncaoHierarquiaRow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(ParemetroFuncaoHierarquiaRow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ParemetroFuncaoHierarquiaRowChanged != null)) {
                    this.ParemetroFuncaoHierarquiaRowChanged(this, new ParemetroFuncaoHierarquiaRowChangeEvent(((ParemetroFuncaoHierarquiaRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ParemetroFuncaoHierarquiaRowChanging != null)) {
                    this.ParemetroFuncaoHierarquiaRowChanging(this, new ParemetroFuncaoHierarquiaRowChangeEvent(((ParemetroFuncaoHierarquiaRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ParemetroFuncaoHierarquiaRowDeleted != null)) {
                    this.ParemetroFuncaoHierarquiaRowDeleted(this, new ParemetroFuncaoHierarquiaRowChangeEvent(((ParemetroFuncaoHierarquiaRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ParemetroFuncaoHierarquiaRowDeleting != null)) {
                    this.ParemetroFuncaoHierarquiaRowDeleting(this, new ParemetroFuncaoHierarquiaRowChangeEvent(((ParemetroFuncaoHierarquiaRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveParemetroFuncaoHierarquiaRow(ParemetroFuncaoHierarquiaRow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                CadeiaAutorizacaoDataSet ds = new CadeiaAutorizacaoDataSet();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "ParemetroFuncaoHierarquiaDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class ParemetroFuncaoHierarquiaRow : System.Data.DataRow {
            
            private ParemetroFuncaoHierarquiaDataTable tableParemetroFuncaoHierarquia;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal ParemetroFuncaoHierarquiaRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableParemetroFuncaoHierarquia = ((ParemetroFuncaoHierarquiaDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string nome {
                get {
                    return ((string)(this[this.tableParemetroFuncaoHierarquia.nomeColumn]));
                }
                set {
                    this[this.tableParemetroFuncaoHierarquia.nomeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public object valor {
                get {
                    try {
                        return ((object)(this[this.tableParemetroFuncaoHierarquia.valorColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'valor\' in table \'ParemetroFuncaoHierarquia\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableParemetroFuncaoHierarquia.valorColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string tipo {
                get {
                    try {
                        return ((string)(this[this.tableParemetroFuncaoHierarquia.tipoColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'tipo\' in table \'ParemetroFuncaoHierarquia\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableParemetroFuncaoHierarquia.tipoColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string tamanho {
                get {
                    try {
                        return ((string)(this[this.tableParemetroFuncaoHierarquia.tamanhoColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'tamanho\' in table \'ParemetroFuncaoHierarquia\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableParemetroFuncaoHierarquia.tamanhoColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsvalorNull() {
                return this.IsNull(this.tableParemetroFuncaoHierarquia.valorColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetvalorNull() {
                this[this.tableParemetroFuncaoHierarquia.valorColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IstipoNull() {
                return this.IsNull(this.tableParemetroFuncaoHierarquia.tipoColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SettipoNull() {
                this[this.tableParemetroFuncaoHierarquia.tipoColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IstamanhoNull() {
                return this.IsNull(this.tableParemetroFuncaoHierarquia.tamanhoColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SettamanhoNull() {
                this[this.tableParemetroFuncaoHierarquia.tamanhoColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class ParemetroFuncaoHierarquiaRowChangeEvent : System.EventArgs {
            
            private ParemetroFuncaoHierarquiaRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ParemetroFuncaoHierarquiaRowChangeEvent(ParemetroFuncaoHierarquiaRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ParemetroFuncaoHierarquiaRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591